## Import Pandas

In [1]:
import pandas as pd

## Load Dataset

In [16]:
df = pd.read_csv("medicine_inventory.csv")
df

                  Medicine  Price  Quantity           Category
0              Paracetamol   25.0      20.0        Pain Relief
1                Ibuprofen   35.0       NaN        Pain Relief
2              Amoxicillin   80.0      12.0        Antibiotics
3                Vitamin C   50.0      30.0        Supplements
4                  Insulin    NaN       5.0           Diabetes
5              Cough Syrup   65.0       8.0         Cold & Flu
6                  Antacid   30.0      15.0          Digestive
7                Eye Drops   45.0       NaN           Eye Care
8                 Bandages   10.0      50.0          First Aid
9           Hand Sanitizer   20.0      25.0            Hygiene
10               Face Mask    5.0     100.0            Hygiene
11             Thermometer  120.0       6.0  Medical Equipment
12  Blood Pressure Monitor  250.0       NaN  Medical Equipment
13     Glucose Test Strips   90.0      18.0           Diabetes
14           Multivitamins   40.0      22.0        Supplements

## Display First and Last Rows

In [4]:
print(df.head())
print(df.tail(2))

      Medicine  Price  Quantity     Category
0  Paracetamol   25.0      20.0  Pain Relief
1    Ibuprofen   35.0       NaN  Pain Relief
2  Amoxicillin   80.0      12.0  Antibiotics
3    Vitamin C   50.0      30.0  Supplements
4      Insulin    NaN       5.0     Diabetes
               Medicine  Price  Quantity     Category
13  Glucose Test Strips   90.0      18.0     Diabetes
14        Multivitamins   40.0      22.0  Supplements

## Check Missing Values

In [5]:
print(df[["Price", "Quantity"]].isnull().sum())

Price       1
Quantity    3
dtype: int64

## Fill Missing Values

In [17]:
df["Price"] = df["Price"].fillna(df["Price"].mean())
df["Quantity"] = df["Quantity"].fillna(1)
df

                  Medicine       Price  Quantity           Category
0              Paracetamol   25.000000      20.0        Pain Relief
1                Ibuprofen   35.000000       1.0        Pain Relief
2              Amoxicillin   80.000000      12.0        Antibiotics
3                Vitamin C   50.000000      30.0        Supplements
4                  Insulin   61.785714       5.0           Diabetes
5              Cough Syrup   65.000000       8.0         Cold & Flu
6                  Antacid   30.000000      15.0          Digestive
7                Eye Drops   45.000000       1.0           Eye Care
8                 Bandages   10.000000      50.0          First Aid
9           Hand Sanitizer   20.000000      25.0            Hygiene
10               Face Mask    5.000000     100.0            Hygiene
11             Thermometer  120.000000       6.0  Medical Equipment
12  Blood Pressure Monitor  250.000000       1.0  Medical Equipment
13     Glucose Test Strips   90.000000      18.0           Diabetes
14           Multivitamins   40.000000      22.0        Supplements

## Create Inventory Value

In [10]:
df["Inventory_Value"] = df["Price"] * df["Quantity"]

## Boolean Filtering

In [11]:
well_stocked = df[df["Quantity"] >= 15]
well_stocked

               Medicine  Price  Quantity     Category  Inventory_Value
0           Paracetamol   25.0      20.0  Pain Relief            500.0
3             Vitamin C   50.0      30.0  Supplements           1500.0
6               Antacid   30.0      15.0    Digestive            450.0
8              Bandages   10.0      50.0    First Aid            500.0
9        Hand Sanitizer   20.0      25.0      Hygiene            500.0
10            Face Mask    5.0     100.0      Hygiene            500.0
13  Glucose Test Strips   90.0      18.0     Diabetes           1620.0
14        Multivitamins   40.0      22.0  Supplements            880.0

## loc Selection

In [12]:
df.loc[5:10, ["Medicine", "Inventory_Value"]]

          Medicine  Inventory_Value
5      Cough Syrup            520.0
6          Antacid            450.0
7        Eye Drops             45.0
8         Bandages            500.0
9   Hand Sanitizer            500.0
10       Face Mask            500.0

## Statistical Summary

In [13]:
df["Inventory_Value"].describe()

count      15.000000
mean      619.261905
std       460.636769
min        35.000000
25%       379.464286
50%       500.000000
75%       800.000000
max      1620.000000
Name: Inventory_Value, dtype: float64

## Save Cleaned Dataset

In [14]:
df.to_csv("cleaned_medicine_inventory.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [ ]:

df["Inventory_Value"].describe()

count      15.000000
mean      619.261905
std       460.636769
min        35.000000
25%       379.464286
50%       500.000000
75%       800.000000
max      1620.000000
Name: Inventory_Value, dtype: float64